services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: doroll
    ports:
      - "5432:5432"
